export const FETCH_FORECAST_REQUEST = "FETCH FORECAST REQUEST";
export const FETCH_FORECAST_SUCCESS = "FETCH FORECAST SUCCESS";
export const FETCH_FORECAST_FAILURE = "FETCH FORECAST FAILURE";
export const CLEAR_FORECAST = "CLEAT FORECAST";
